Repository TeamCatchMe/Server, pull requests merged in 2023-01, with the labels that each got.

#4 chore: 프로젝트 리팩토링
  src/app.config.ts
  src/config/services/api-config.service.ts
  src/libraries/logger.service.ts
  src/main.ts
Labels: enhancement, help wanted

#2 test: UserService Mock test 추가
  test/v1/user/unit/user.service.test.ts
Labels: help wanted, test

#7 test: AuthService에 대한 Mock Service 추가
  test/v1/auth/unit/auth.service.test.ts
Labels: help wanted, test

#8 feat: Auth Service 로직 구현
  prisma/schema.prisma
  src/common/constants/responseMessage.ts
  src/common/libraries/logger.service.ts
  src/common/middlewares/logger.middleware.ts
  src/config/services/api-config.service.ts
  src/libraries/logger.service.ts
  src/main.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/auth/auth.interface.ts
  src/modules/v1/auth/auth.module.ts
  src/modules/v1/auth/auth.repository.ts
  src/modules/v1/auth/auth.service.ts
  src/modules/v1/auth/common/auth.type.ts
  src/modules/v1/auth/dto/auth.res.dto.ts
  src/modules/v1/user/user.module.ts
  src/modules/v1/v1.module.ts
  test/v1/auth/unit/auth.service.test.ts
  test/v1/user/unit/user.service.test.ts
Labels: enhancement, help wanted

#12 [Feat] Auth API 구현
  src/app.module.ts
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/auth/AuthLoginSuccess.ts
  src/common/constants/swagger/domain/auth/AuthSignupSuccess.ts
  src/common/constants/swagger/domain/auth/AuthTokenGetAccepted.ts
  src/common/constants/swagger/domain/auth/AuthTokenGetSuccess.ts
  src/common/constants/swagger/domain/auth/AuthWithdrawSuccess.ts
  src/common/exceptions/http-exception.filter.ts
  src/config/common.module.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/auth/auth.module.ts
  src/modules/v1/auth/auth.service.ts
  src/modules/v1/auth/common/auth.strategy.ts
  src/modules/v1/auth/common/auth.type.ts
  src/modules/v1/auth/config/auth.config.ts
  src/modules/v1/auth/dto/auth-login.req.dto.ts
  src/modules/v1/auth/dto/auth-signup.req.dto.ts
  src/modules/v1/auth/dto/auth-token-get.header.dto.ts
  src/modules/v1/auth/dto/auth-token-get.res.dto.ts
  src/modules/v1/user/dto/user.dto.ts
  src/modules/v1/user/user.controller.ts
  src/modules/v1/v1.module.ts
  test/v1/auth/unit/auth.service.test.ts
Labels: enhancement, help wanted

#17 [test] ActivityService에 대한 Mock 테스트 추가
  test/v1/activity/unit/activity.service.test.ts
Labels: test

#13 [feat] User API 구현
  src/common/constants/swagger/domain/user/UserDuplicateCheckSuccess.ts
  src/common/constants/swagger/domain/user/UserPatchNicknameSuccess.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/auth/auth.module.ts
  src/modules/v1/user/dto/user-nickname.patch.res.dto.ts
  src/modules/v1/user/dto/user-nickname.query.dto.ts
  src/modules/v1/user/user.controller.ts
  src/modules/v1/user/user.module.ts
  src/modules/v1/user/user.service.ts
  test/v1/user/unit/user.service.test.ts
Labels: enhancement, help wanted

#19 [feat] Character 생성/수정 API 구현
  package.json
  prisma/schema.prisma
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/character/CharacterCreateSuccess.ts
  src/common/constants/swagger/domain/character/CharacterEditSuccess.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.module.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/character-create.req.dto.ts
  src/modules/v1/character/dto/character-edit.req.dto.ts
  src/modules/v1/character/dto/character.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
  src/modules/v1/v1.module.ts
  test/v1/character/unit/character.service.test.ts
  yarn.lock
Labels: enhancement

#20 [feat] Activity API 구현
  prisma/schema.prisma
  src/common/constants/responseMessage.ts
  src/config/routes.config.ts
  src/modules/v1/activity/activity.controller.ts
  src/modules/v1/activity/activity.module.ts
  src/modules/v1/activity/activity.repository.ts
  src/modules/v1/activity/activity.service.ts
  src/modules/v1/activity/dto/activity-create.req.dto.ts
  src/modules/v1/activity/dto/activity-date.params.dto.ts
  src/modules/v1/activity/dto/activity-update.req.dto.ts
  src/modules/v1/activity/dto/activity.dto.ts
  src/modules/v1/activity/dto/activity.params.dto.ts
  src/modules/v1/activity/dto/activity.query.dto.ts
  src/modules/v1/activity/interfaces/activity-repository.interface.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/user/user.controller.ts
  src/modules/v1/v1.module.ts
  test/v1/activity/unit/activity.service.test.ts
Labels: enhancement, help wanted

#21 [feat] Character 차단 / 목록조회 API 구현
  prisma/schema.prisma
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/character/CharacterBlockSuccess.ts
  src/common/constants/swagger/domain/character/CharacterGetFromMainSuccess.ts
  src/common/constants/swagger/domain/character/CharactersListSuccess.ts
  src/modules/v1/block/block.repository.ts
  src/modules/v1/block/interface/block-repository.interface.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.module.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/character-block.req.dto.ts
  src/modules/v1/character/dto/character-get-from-main.res.dto.ts
  src/modules/v1/character/dto/characters.res.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
  src/modules/v1/character/interfaces/sort-type.ts
  test/v1/character/unit/character.service.test.ts
Labels: enhancement
