Repository TeamCatchMe/Server, pull requests merged in 2023-03, with the labels that each got.

#23 [feat] Activity API 추가 및 기타 사항 업데이트
  prisma/schema.prisma
  src/app.config.ts
  src/common/libraries/slack/slack.ts
  src/modules/v1/activity/activity.controller.ts
  src/modules/v1/activity/activity.service.ts
  src/modules/v1/character/character.service.ts
Labels: enhancement, Done 👏

#27 [feat] 캐츄 정보 조회 API , 둘러보기 API
  src/common/constants/responseMessage.ts
  src/config/routes.config.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/character-detail.params.dto.ts
  src/modules/v1/character/dto/character-get-detail.res.dto.ts
  src/modules/v1/character/dto/characters.res.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
Labels: enhancement

#28 [fix] Auth API 내 분기처리 및 스웨거 수정
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/auth/AuthAcceptedSuccess.ts
  src/common/constants/swagger/domain/auth/AuthSignupSuccess.ts
  src/modules/v1/auth/auth.controller.ts
  src/modules/v1/auth/auth.service.ts
Labels: Done 👏

#29 [feat] 캐릭터별 활동 조회 API 구현
  src/common/constants/swagger/domain/activity/ActivityCharacterGetSuccess.ts
  src/common/constants/swagger/domain/activity/ActivityCreateSuccess.ts
  src/common/constants/swagger/domain/activity/ActivityDeleteSuccess.ts
  src/common/constants/swagger/domain/activity/ActivityUpdateSuccess.ts
  src/config/routes.config.ts
  src/modules/v1/activity/activity.controller.ts
  src/modules/v1/activity/activity.repository.ts
  src/modules/v1/activity/activity.service.ts
  src/modules/v1/activity/dto/activity-character.params.dto.ts
  src/modules/v1/activity/interfaces/activity-repository.interface.ts
  src/modules/v1/character/dto/character-block.req.dto.ts
  src/modules/v1/character/dto/character.dto.ts
Labels: enhancement, Done 👏

#30 [feat] 캐릭터 삭제 API 구현
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/character/CharacterDeleteSuccess.ts
  src/config/routes.config.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
Labels: enhancement, Done 👏

#32 [feat] 캐츄 둘러보기 완성
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/character/CharacterGetFromLookingSuccess.ts
  src/config/routes.config.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/characters-get-looking.res.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
Labels: enhancement
