Repository TeamCatchMe/Server, pull requests merged in 2023-04, with the labels that each got.

#34 [feat] 캘린더 관련 캐츄 조회 작업
  src/common/constants/responseMessage.ts
  src/common/constants/swagger/domain/character/CharacterGetFromCalenderSuccess.ts
  src/common/constants/swagger/domain/character/CharacterGetFromSpecificDateSuccess.ts
  src/config/routes.config.ts
  src/modules/v1/activity/activity.controller.ts
  src/modules/v1/activity/activity.repository.ts
  src/modules/v1/activity/activity.service.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.module.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/character-get-calender.res.dto.ts
  src/modules/v1/character/dto/character-get-specificDate.res.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
Labels: enhancement

#36 [fix] 둘러보기 response 형식 수정 및 캐치 지수 업데이트 안되는 문제 해결
  src/modules/v1/activity/interfaces/activity-repository.interface.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/characters-get-looking.res.dto.ts
Labels: bug

#38 [fix] 글 수정 시 이미지 옵셔널 처리 및 스웨거 일부 수정
  src/modules/v1/activity/activity.controller.ts
  src/modules/v1/user/user.controller.ts
Labels: Done 👏

#40 [fix] 둘러보기 조회시 캐릭터 정렬 안되는 문제 해결
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/character-get-calender.res.dto.ts
Labels: bug

#42 Fix/character/#41
  src/modules/v1/activity/activity.repository.ts
  src/modules/v1/activity/interfaces/activity-repository.interface.ts
  src/modules/v1/character/character.controller.ts
  src/modules/v1/character/character.repository.ts
  src/modules/v1/character/character.service.ts
  src/modules/v1/character/dto/characters-get-looking.res.dto.ts
  src/modules/v1/character/interfaces/character-repository.interface.ts
Labels: bug
